@ECHO OFF
SETLOCAL

SET WATCOM=C:\WATCOM
SET PATH=%WATCOM%\BINW;C:\WINDOWS\SYSTEM32;C:\WINDOWS
SET INCLUDE=%WATCOM%\H
SET LIB=%WATCOM%\LIB286;%WATCOM%\LIB286\DOS

CD /D "%~dp0"

ECHO Compiling for 16-bit DOS...
WCC -bt=dos -ml -ox ITE8888.C
IF NOT EXIST ITE8888.OBJ GOTO FAIL

ECHO Linking...
WLINK system dos file ITE8888.OBJ library clibl name ITE8888.EXE
IF NOT EXIST ITE8888.EXE GOTO FAIL

ECHO Success!
DIR ITE8888.EXE
DEL ITE8888.OBJ
GOTO END

:FAIL
ECHO Build failed
PAUSE

:END
ENDLOCAL