@echo off
echo Open Watcom Build Environment

SET WATCOM=C:\WATCOM
SET PATH=C:\WATCOM\BINW;%PATH%
SET PATH=C:\WATCOM\BINNT;%PATH%

SET INCLUDE=C:\WATCOM\H;%INCLUDE%
SET INCLUDE=C:\WATCOM\H\NT;%INCLUDE%
SET INCLUDE=%INCLUDE%;C:\WATCOM\H\NT\DIRECTX
SET INCLUDE=%INCLUDE%;C:\WATCOM\H\NT\DDK

SET EDPATH=C:\WATCOM\EDDAT
SET WHTMLHELP=C:\WATCOM\BINNT\HELP
SET WIPFC=C:\WATCOM\WIPFC

cd /d G:\PCIe-PCI-ISA\DFT_VMDA8\it8888vdma_dos